/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pokedexrewardsgradle;

import org.bukkit.plugin.PluginLogger;
import org.bukkit.plugin.java.JavaPlugin;

import pokedexrewardsgradle.Commands.DexRewards;
import pokedexrewardsgradle.Commands.PokehealIntercept;
import pokedexrewardsgradle.Events.OnCatchEvent;

/**
 * Hello world!
 *
 * 
 */
public final class PokedexRewardsMain extends JavaPlugin {

    @Override
    public void onEnable() {
        //Debug log
        getLogger().info("onEnable has been invoked!");

        getServer().getPluginManager().registerEvents(new OnCatchEvent((PluginLogger) getLogger()), this);
        this.getCommand("dexreward").setExecutor(new DexRewards((PluginLogger) getLogger()));
        this.getCommand("healer").setExecutor(new PokehealIntercept((PluginLogger) getLogger()));
    }

    @Override
    public void onDisable() {
        getLogger().info("onDisable has been invoked!");
    }
}
